basic.forever(function () {
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 45)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 45)
    basic.pause(1500)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 45)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 45)
    basic.pause(1500)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 45)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 45)
    basic.pause(1500)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 45)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 45)
    basic.pause(1500)
})
